# Site settings
title: mylog
baseurl: ""
url: "https://wisoftmy.github.io/"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: MinYoung Park 
  desc:  
  email: minyoung@edu.hanbat.ac.kr
  selfie: assets/img/profile.jpeg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: Test
  flickr:
  github: https://github.com/wisoftMY 
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/kssim/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Protfolio Schema
--- 
layout: Microservice 프로젝트
title: https://www.notion.so/wsminyoung/Microservice-a90dd575cff04f0c81ec4717762d353a  
info: 
tech: 
type:
---
layout: 기업 프로젝트(화재 방지 스마트 밸브) 
title: https://www.notion.so/wsminyoung/a7da5e4e073d4d18860b3f4785333b7d
info: 
tech: 
type: 
---
# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
